//import './jsxstudy/jsx-study1';
//import './jsxstudy/jsx-study2';
//npm start
//import './component-basic/first-component';
//import './component-basic/props-basic';
//import './component-basic/props-children';
//import './component-intermediate/state-study-with-inner-object';
//import './component-intermediate/mainpulate.js'
//import './component-intermediate/todo-app-demo.js'
//import './use-effect-demo/use-effect-intro.js'
//import './use-effect-demo/use-effect-using-local-storage.js'
//import './use-effect-demo/use-effect-unmount.js'
//import './use-effect-demo/use-effect-unmount-deps.js'
//import './component-intermediate/counter-demo.js'
//import './use-effect-demo/timer_cilickgame.js'
//import './use-effect-demo/use-effect-fetch-api.js'
import './component-advanced/reservation-form'